metrics:
  bstats: true

models:
  namespace: "modelengine"
  join-send-delay: 20 # ms
  spawn-send-delay: 1 # ms
  properties-send-delay: 1 # ms
  entity-position-update-period: 35 # ms
  thread-pool-size: 4

options:
  debug:
    spawn: false
    animations: false
    send-data: false
    location: false
    death: false
  hooks:
    floodgate: true # Recommended method